services:
  napgram:
    # 可用 latest 或指定版本号（例如 v0.1.1）
    image: ghcr.io/napgram/napgram:latest
    container_name: napgram
    user: "1000" # 使用与 NapCat 相同的 UID，避免文件权限问题
    ports:
      - "8080:8080"
    environment:
      # -----------------------------------------------------------------------------
      # 必填：Telegram Bot
      # -----------------------------------------------------------------------------
      TG_API_ID: "123456"
      TG_API_HASH: "replace_me"
      TG_BOT_TOKEN: "replace_me"

      # -----------------------------------------------------------------------------
      # 必填：Web / 管理
      # -----------------------------------------------------------------------------
      LISTEN_PORT: "8080"
      WEB_ENDPOINT: "http://localhost:8080"
      ADMIN_TOKEN: "replace_me"

      # -----------------------------------------------------------------------------
      # 存储路径（可选；不改则用默认值）
      # -----------------------------------------------------------------------------
      DATA_DIR: "/app/data"
      CACHE_DIR: "/app/data/cache"

      # -----------------------------------------------------------------------------
      # 日志（可选）
      # -----------------------------------------------------------------------------
      LOG_LEVEL: "info"
      LOG_FILE_LEVEL: "debug"
      LOG_FILE: "/app/data/logs/app.log"
      OICQ_LOG_LEVEL: "warn"
      TG_LOG_LEVEL: "warn"

      # -----------------------------------------------------------------------------
      # Telegram 连接（可选）
      # -----------------------------------------------------------------------------
      TG_CONNECTION: "tcp" # tcp/websocket
      TG_INITIAL_DCID: "" # 例如 "5"
      TG_INITIAL_SERVER: "" # 例如 "91.108.56.174"
      TG_USE_TEST_DC: "false"
      IPV6: "false"

      # -----------------------------------------------------------------------------
      # 管理员（可选）
      # -----------------------------------------------------------------------------
      ADMIN_QQ: ""
      ADMIN_TG: ""

      # -----------------------------------------------------------------------------
      # 代理（可选）
      # -----------------------------------------------------------------------------
      PROXY_IP: ""
      PROXY_PORT: ""
      PROXY_USERNAME: ""
      PROXY_PASSWORD: ""

      # -----------------------------------------------------------------------------
      # NapCat / 签名（可选）
      # -----------------------------------------------------------------------------
      NAPCAT_WS_URL: "ws://napcat:3001"
      SIGN_API: ""
      SIGN_VER: ""

      # -----------------------------------------------------------------------------
      # 外部工具（可选）
      # -----------------------------------------------------------------------------
      FFMPEG_PATH: ""
      FFPROBE_PATH: ""
      TGS_TO_GIF: "tgs_to_gif"

      # -----------------------------------------------------------------------------
      # CRV（可选）
      # -----------------------------------------------------------------------------
      CRV_API: ""
      CRV_VIEWER_APP: ""
      CRV_KEY: ""

      # -----------------------------------------------------------------------------
      # UI（可选：本地 dist 或反代）
      # -----------------------------------------------------------------------------
      UI_PATH: "/app/web/dist"
      UI_PROXY: ""
      INTERNAL_WEB_ENDPOINT: ""

      # -----------------------------------------------------------------------------
      # 功能开关（可选）
      # -----------------------------------------------------------------------------
      DISABLE_FILE_UPLOAD_TIP: "false"
      IMAGE_SUMMARY: ""
      ENABLE_FEATURE_MANAGER: "false"
      POSTHOG_OPTOUT: "false"
      SHOW_NICKNAME_MODE: "11"
      FORWARD_MODE: "11"
      ENABLE_AUTO_RECALL: "true"
      ENABLE_OFFLINE_NOTIFICATION: "true"
      OFFLINE_NOTIFICATION_COOLDOWN: "3600000"

      # -----------------------------------------------------------------------------
      # 构建信息（可选；不改则用默认值）
      # -----------------------------------------------------------------------------
      REPO: "Local Build"
      REF: "Local Build"
      COMMIT: "Local Build"

      # -----------------------------------------------------------------------------
      # 数据库连接（Prisma 使用；需与下方 postgres 服务凭据一致）
      # -----------------------------------------------------------------------------
      DATABASE_URL: "postgres://napgram_user:secure_password_here@postgres:5432/napgram"

      # 时区（可选）
      TZ: "Asia/Shanghai"
    volumes:
      - ./data:/app/data
      # 挂载 NapCat 的 QQ 数据目录以访问媒体文件
      - /path/to/napcat/data:/app/.config/QQ
    depends_on:
      - postgres
    command: sh -c "npx prisma db push && node build/index.js"
    networks:
      - napgram_net
    restart: always

  # PostgreSQL 数据库服务
  postgres:
    image: postgres:14-alpine
    container_name: napgram-postgres
    restart: always
    environment:
      POSTGRES_DB: napgram
      POSTGRES_USER: napgram_user
      POSTGRES_PASSWORD: secure_password_here
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - napgram_net

networks:
  napgram_net:
    driver: bridge
  # 如需连接到外部服务，可添加：
  # external_network:
  #   external: true

volumes:
  postgres_data:
