import { execFile } from 'node:child_process'
import fs from 'node:fs/promises'
import os from 'node:os'
import path from 'node:path'
import { promisify } from 'node:util'
import { gunzipSync } from 'node:zlib'
import { getLogger } from '../../logger'

const execFileAsync = promisify(execFile)
const logger = getLogger('TGSConverter')

export default async function tgsToGif(tgsPath: string, outputPath?: string): Promise<string> {
  const outPath = outputPath || tgsPath.replace(/\.tgs$/i, '.gif')
  const tempDir = await fs.mkdtemp(path.join(os.tmpdir(), 'tgs-'))

  try {
    logger.debug(`[tgs2gif] Converting ${tgsPath} to ${outPath}`)

    // 1. 读取并解压TGS文件（TGS = gzipped Lottie JSON）
    const tgsBuffer = await fs.readFile(tgsPath)
    const lottieJson = gunzipSync(tgsBuffer).toString()
    const jsonPath = path.join(tempDir, 'animation.json')
    await fs.writeFile(jsonPath, lottieJson)
    logger.debug(`[tgs2gif] TGS decompressed to ${jsonPath}`)

    // 2. 使用lottie_to_png渲染每一帧为PNG
    logger.debug(`[tgs2gif] Rendering frames with lottie_to_png...`)

    await execFileAsync('/usr/bin/lottie_to_png', [
      '--width',
      '512',
      '--height',
      '512',
      '--output',
      tempDir,
      jsonPath,
    ])

    // 3. 收集生成的PNG文件
    const allFiles = await fs.readdir(tempDir)
    const pngFiles = allFiles
      .filter(f => f.endsWith('.png'))
      .sort()
      .map(f => path.join(tempDir, f))

    if (pngFiles.length === 0) {
      throw new Error('No PNG frames generated by lottie_to_png')
    }

    logger.debug(`[tgs2gif] Generated ${pngFiles.length} frames, encoding to GIF...`)

    // 4. 使用gifski编码成GIF
    await execFileAsync('/usr/bin/gifski', [
      '--quiet',
      '-o',
      outPath,
      '--fps',
      '50',
      '--width',
      '512',
      '--height',
      '512',
      '--quality',
      '90',
      ...pngFiles,
    ])

    logger.info(`[tgs2gif] Successfully converted to ${outPath}`)
    return outPath
  }
  catch (error) {
    logger.error(`[tgs2gif] Conversion failed:`, error)
    throw error
  }
  finally {
    // 清理临时文件
    try {
      await fs.rm(tempDir, { recursive: true, force: true })
    }
    catch (cleanupError) {
      logger.warn(`[tgs2gif] Failed to cleanup temp dir:`, cleanupError)
    }
  }
}
